### ISSUE TITLE
[bug] [AuthMe] Failed to send a mail to

### ISSUE THREAD

**Issue by ghost** [HaHaWTH/AuthMeReReloaded#83] opened 2023-12-18 12:27 UTC
### What behaviour is observed?

I'm trying to make email system with gmail and biz.mail.ru mailAccount, mailPassword, mailSenderName changed and     mailSMTP: smtp.mail.ru 465

### Expected behaviour

,

### To Reproduce

,

### Plugin list

,

### Server Implementation

Standalone server (no proxy)

### Database Implementation

SQLite

### AuthMe Version

from release (today)

### Error log (if applicable)

,

### Configuration

,

**Comment by HaHaWTH** [comment] 2023-12-18 16:08
Will this occur on the original version? (AuthmeReloaded)

**Comment by HaHaWTH** [comment] 2024-02-12 21:02
Yeah, I tested on outlook, hotmail, 163 mail and biz mail, they all worked as expected.
I can't reproduce this issue tbh, but gmail is not working can be confirmed.

**Comment by HaHaWTH** [comment] 2024-03-31 05:17
Tested gmail on latest build, works properly.

**Comment by HaHaWTH** [comment] 2024-04-24 12:12
This should be fixed in latest dev build

**Closed** 2024-05-29 13:58 UTC
Labels: bug:Spigot, Minor, Fixed in Dev, Priority: Medium, upstream
